#!/usr/bin/env python3
import multiprocessing
import socket
import time
from string import Template
def enviarArchivo(i):
    serversocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    serversocket.connect(('localhost', 5000))
    mensaje = """
	#include <stdio.h>
	int main () {
      int n = 600;
      for(int i=1; i<=n; ++i) {
        for(int i=1; i<=n; ++i) {
          for(int i=1; i<=n; ++i) {
          }
        }
      }
	  printf("Hola");
	  printf("Como estan %s");
	  return 0;
	}
	""" % (str(i))
    serversocket.send(str.encode(str(mensaje)))
    serverMensaje = serversocket.recv(1024)
    print(serverMensaje)
    return

if __name__ == '__main__':
    jobs = []
    for i in range(20):
        time.sleep(0.1)
        p = multiprocessing.Process(target=enviarArchivo, args=(i,))
        jobs.append(p)
        p.start()
