#!/usr/bin/env python3
import multiprocessing
import socket
import time
from string import Template
import json
import random

def enviarArchivo(i):
    serversocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    serversocket.connect(('localhost', 5000))
    opciones = [';', '']
    mensaje = """
	#include <stdio.h>
	int main () {
      int n = 600;
      for(int i=1; i<=n; ++i) {
        for(int i=1; i<=n; ++i) {
          for(int i=1; i<=n; ++i) {
          }
        }
      }
	  printf("Hola");
	  printf("Como estan %s")%s
	  return 0;
	}
	""" % (str(i), random.choice(opciones))
    serversocket.send(str.encode(str(mensaje)))
    serverMensaje = serversocket.recv(1024)
    mensajeLimpiado = serverMensaje.decode("utf-8")
    try:
        o = json.loads(mensajeLimpiado, strict=False)
        print(o['datos'])
    except ValueError:
        print("\n\n===== ERROR =========")
        print(mensajeLimpiado)
        print("\n")
    return

if __name__ == '__main__':
    jobs = []
    for i in range(20):
        time.sleep(0.1)
        p = multiprocessing.Process(target=enviarArchivo, args=(i,))
        jobs.append(p)
        p.start()
